name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying code via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/ti4_bag_draft
            git pull origin main
            
            # Установка зависимостей
            npm install
            npm install --prefix client
            npm install --prefix server
            
            # Перезапуск PM2 с именем процесса ti4_bag_draft
            pm2 delete ti4bag_draft || true
            pm2 start server/index.js --name "ti4_bag_draft"
            pm2 save